FROM eclipse-temurin:17-alpine


RUN apk add --no-cache python3 py3-pip


ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="$JAVA_HOME/bin:/usr/bin/python3:$PATH"

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir /home/codes

# ENTRYPOINT ["/bin/sh", "-c"]
CMD ["python", "./app.py"]
